services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: edge_lab
      POSTGRES_USER: edge
      POSTGRES_PASSWORD: edge
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/db_data

volumes:
  db_data: